# Generated by Django 3.1.4 on 2020-12-30 15:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(max_length=64)),
                ('img', models.ImageField(blank=True, null=True, upload_to='post_img')),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 12, 30, 17, 19, 31, 755277))),
                ('active', models.BooleanField(default=True)),
                ('seller', models.CharField(max_length=50)),
                ('starting_bid', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 12, 30, 17, 19, 31, 756277))),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 12, 30, 17, 19, 31, 757277))),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
