# Generated by Django 3.1.4 on 2021-01-03 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210103_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 17, 1, 54, 215380)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 17, 1, 54, 214380)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 17, 1, 54, 212380)),
        ),
    ]
