# Generated by Django 3.1.4 on 2021-01-04 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210104_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 22, 37, 3, 801364)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 22, 37, 3, 800364)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 22, 37, 3, 799364)),
        ),
        migrations.AlterField(
            model_name='post',
            name='mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
